language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:
  - codecov/example-r

after_success:
  - Rscript -e 'library(covr);codecov()'

codecov:
  token: 08828d9d-437d-4e56-a0d1-50fd8a886dcb
