# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' checks the same headers are in both data frames past into the function.
#' Helper function for dataFrameHeadersCheck.
#'
#' @param leftDataFrame data frame.
#' @param rightDataFrame data frame.
#' @return bool true if the data frames have the same headers else false.
sameHeaders <- function(leftDataFrame, rightDataFrame) {
    .Call('_RcsvgPP_sameHeaders', PACKAGE = 'RcsvgPP', leftDataFrame, rightDataFrame)
}

#' checks two different data frames have the same number of columns and the same headers if requested.
#' Helper function for indexOfDiffDataframeInVector.
#'
#' @param leftDataFrame data frame.
#' @param rightDataFrame data frame.
#' @param checkHeaderNames bool true if header names required checking.
#' @return bool true if the data frames have the same number of columns and if required the headers are the same else false.
dataFrameHeadersCheck <- function(leftDataFrame, rightDataFrame, checkHeaderNames) {
    .Call('_RcsvgPP_dataFrameHeadersCheck', PACKAGE = 'RcsvgPP', leftDataFrame, rightDataFrame, checkHeaderNames)
}

#' removes data frames from a vector if they do not have the same header structure as the first data frame in the vector.
#'
#' @param dataframeVector vector of data frames.
#' @param checkHeaderNames bool true if header names required checking for the helper function dataFrameHeadersCheck.
#' @return vector of data frames.
keepDataframesWithSameHeaders <- function(dataframeVector, checkHeaderNames) {
    .Call('_RcsvgPP_keepDataframesWithSameHeaders', PACKAGE = 'RcsvgPP', dataframeVector, checkHeaderNames)
}

#' Moves a string in a charcater vector to the start of the vector if it matches the string input.
#'
#' @param x String The string value to match in the character vector to move to the front.
#' @param chrVector character vector.
#' @return character vector.
moveToIndexOne <- function(x, chrVector) {
    .Call('_RcsvgPP_moveToIndexOne', PACKAGE = 'RcsvgPP', x, chrVector)
}

#' Sets all the data frames in a vector to have the same headers as the first data frame in the vector.
#'
#' @param dataframeVector vector of data frames.
#' @return Vector of data frames with all the column names the same as the first data frame.
setDataframeColNamesToFirstDataframe <- function(dataframeVector) {
    .Call('_RcsvgPP_setDataframeColNamesToFirstDataframe', PACKAGE = 'RcsvgPP', dataframeVector)
}

