# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DataFrameHeadersCheck <- function(leftDataFrame, rightDataFrame, checkHeaderNames) {
    .Call('_RcsvgPP_DataFrameHeadersCheck', PACKAGE = 'RcsvgPP', leftDataFrame, rightDataFrame, checkHeaderNames)
}

moveToIndexOne <- function(x, chrVector) {
    .Call('_RcsvgPP_moveToIndexOne', PACKAGE = 'RcsvgPP', x, chrVector)
}

sameHeaders <- function(leftDataFrame, rightDataFrame) {
    .Call('_RcsvgPP_sameHeaders', PACKAGE = 'RcsvgPP', leftDataFrame, rightDataFrame)
}

